
package fr.careco.aaa.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.8-patch-01
 * 2013-11-26T11:15:21.972+01:00
 * Generated source version: 2.4.8-patch-01
 */

@WebFault(name = "NumeroImmatriculationInconnu", targetNamespace = "http://aaa.asso.fr/sivin/schemas")
public class NumeroImmatriculationInconnu_Exception extends Exception {
    
    private fr.careco.aaa.ws.NumeroImmatriculationInconnu numeroImmatriculationInconnu;

    public NumeroImmatriculationInconnu_Exception() {
        super();
    }
    
    public NumeroImmatriculationInconnu_Exception(String message) {
        super(message);
    }
    
    public NumeroImmatriculationInconnu_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public NumeroImmatriculationInconnu_Exception(String message, fr.careco.aaa.ws.NumeroImmatriculationInconnu numeroImmatriculationInconnu) {
        super(message);
        this.numeroImmatriculationInconnu = numeroImmatriculationInconnu;
    }

    public NumeroImmatriculationInconnu_Exception(String message, fr.careco.aaa.ws.NumeroImmatriculationInconnu numeroImmatriculationInconnu, Throwable cause) {
        super(message, cause);
        this.numeroImmatriculationInconnu = numeroImmatriculationInconnu;
    }

    public fr.careco.aaa.ws.NumeroImmatriculationInconnu getFaultInfo() {
        return this.numeroImmatriculationInconnu;
    }
}
