package fr.careco.aaa.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.8-patch-01
 * 2013-11-26T11:15:22.078+01:00
 * Generated source version: 2.4.8-patch-01
 * 
 */
@WebServiceClient(name = "WS_SiVin_Consulter", 
                  wsdlLocation = "http://ws.auto-mra.com/mra/services/WS_SiVin_Consulter?wsdl",
                  targetNamespace = "http://aaa.asso.fr/sivin") 
public class WSSiVinConsulter extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://aaa.asso.fr/sivin", "WS_SiVin_Consulter");
    public final static QName WSSiVinConsulterSOAP12Port = new QName("http://aaa.asso.fr/sivin", "WS_SiVin_ConsulterSOAP12port");
    public final static QName WSSiVinConsulterSOAP11Port = new QName("http://aaa.asso.fr/sivin", "WS_SiVin_ConsulterSOAP11port");
    static {
        URL url = null;
        try {
            url = new URL("http://ws.auto-mra.com/mra/services/WS_SiVin_Consulter?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WSSiVinConsulter.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://ws.auto-mra.com/mra/services/WS_SiVin_Consulter?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WSSiVinConsulter(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSSiVinConsulter(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSSiVinConsulter() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSSiVinConsulter(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSSiVinConsulter(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSSiVinConsulter(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns WSSiVinConsulterPortType
     */
    @WebEndpoint(name = "WS_SiVin_ConsulterSOAP12port")
    public WSSiVinConsulterPortType getWSSiVinConsulterSOAP12Port() {
        return super.getPort(WSSiVinConsulterSOAP12Port, WSSiVinConsulterPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSSiVinConsulterPortType
     */
    @WebEndpoint(name = "WS_SiVin_ConsulterSOAP12port")
    public WSSiVinConsulterPortType getWSSiVinConsulterSOAP12Port(WebServiceFeature... features) {
        return super.getPort(WSSiVinConsulterSOAP12Port, WSSiVinConsulterPortType.class, features);
    }
    /**
     *
     * @return
     *     returns WSSiVinConsulterPortType
     */
    @WebEndpoint(name = "WS_SiVin_ConsulterSOAP11port")
    public WSSiVinConsulterPortType getWSSiVinConsulterSOAP11Port() {
        return super.getPort(WSSiVinConsulterSOAP11Port, WSSiVinConsulterPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSSiVinConsulterPortType
     */
    @WebEndpoint(name = "WS_SiVin_ConsulterSOAP11port")
    public WSSiVinConsulterPortType getWSSiVinConsulterSOAP11Port(WebServiceFeature... features) {
        return super.getPort(WSSiVinConsulterSOAP11Port, WSSiVinConsulterPortType.class, features);
    }

}
