package fr.careco.aaa.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.8-patch-01
 * 2013-11-26T11:15:22.050+01:00
 * Generated source version: 2.4.8-patch-01
 * 
 */
@WebService(targetNamespace = "http://aaa.asso.fr/sivin", name = "WS_SiVin_ConsulterPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface WSSiVinConsulterPortType {

    @WebResult(name = "return", targetNamespace = "http://aaa.asso.fr/sivin/schemas")
    @Action(input = "urn:WS_SiVin_Consulter_VehiculeParImmat", output = "//aaa.asso.fr/sivin/WS_SiVin_ConsulterPortType/WS_SiVin_Consulter_VehiculeParImmatResponse", fault = {@FaultAction(className = NumeroImmatriculationInconnu_Exception.class, value = "urn:WS_SiVin_Consulter_VehiculeParImmatNumeroImmatriculationInconnu"), @FaultAction(className = BaseDeDonneeInaccessible_Exception.class, value = "urn:WS_SiVin_Consulter_VehiculeParImmatBaseDeDonneeInaccessible"), @FaultAction(className = Quota_Exception.class, value = "urn:WS_SiVin_Consulter_VehiculeParImmatQuota")})
    @RequestWrapper(localName = "WS_SiVin_Consulter_VehiculeParImmat", targetNamespace = "http://aaa.asso.fr/sivin/schemas", className = "fr.careco.aaa.ws.WSSiVinConsulterVehiculeParImmat")
    @WebMethod(operationName = "WS_SiVin_Consulter_VehiculeParImmat", action = "urn:WS_SiVin_Consulter_VehiculeParImmat")
    @ResponseWrapper(localName = "WS_SiVin_Consulter_VehiculeResponse", targetNamespace = "http://aaa.asso.fr/sivin/schemas", className = "fr.careco.aaa.ws.WSSiVinConsulterVehiculeResponse")
    public fr.careco.aaa.ws.Vehicule wsSiVinConsulterVehiculeParImmat(
        @WebParam(name = "immat", targetNamespace = "http://aaa.asso.fr/sivin/schemas")
        java.lang.String immat,
        @WebParam(name = "Nom", targetNamespace = "http://aaa.asso.fr/sivin/schemas")
        java.lang.String nom,
        @WebParam(name = "DateDCG", targetNamespace = "http://aaa.asso.fr/sivin/schemas")
        fr.careco.aaa.ws.Date dateDCG,
        @WebParam(name = "Date1erCir", targetNamespace = "http://aaa.asso.fr/sivin/schemas")
        fr.careco.aaa.ws.Date date1ErCir,
        @WebParam(name = "numeroSerie", targetNamespace = "http://aaa.asso.fr/sivin/schemas")
        java.lang.String numeroSerie
    ) throws NumeroImmatriculationInconnu_Exception, BaseDeDonneeInaccessible_Exception, Quota_Exception;

    @WebResult(name = "return", targetNamespace = "http://aaa.asso.fr/sivin/schemas")
    @Action(input = "urn:WS_SiVin_Consulter_FlotteParSiren", output = "//aaa.asso.fr/sivin/WS_SiVin_ConsulterPortType/WS_SiVin_Consulter_FlotteParSirenResponse", fault = {@FaultAction(className = BaseDeDonneeInaccessible_Exception.class, value = "urn:WS_SiVin_Consulter_FlotteParSirenBaseDeDonneeInaccessible"), @FaultAction(className = Quota_Exception.class, value = "urn:WS_SiVin_Consulter_FlotteParSirenQuota"), @FaultAction(className = NumeroSirenInconnu_Exception.class, value = "urn:WS_SiVin_Consulter_FlotteParSirenNumeroSirenInconnu")})
    @RequestWrapper(localName = "WS_SiVin_Consulter_FlotteParSiren", targetNamespace = "http://aaa.asso.fr/sivin/schemas", className = "fr.careco.aaa.ws.WSSiVinConsulterFlotteParSiren")
    @WebMethod(operationName = "WS_SiVin_Consulter_FlotteParSiren", action = "urn:WS_SiVin_Consulter_FlotteParSiren")
    @ResponseWrapper(localName = "WS_SiVin_Consulter_FlotteParSirenResponse", targetNamespace = "http://aaa.asso.fr/sivin/schemas", className = "fr.careco.aaa.ws.WSSiVinConsulterFlotteParSirenResponse")
    public java.util.List<fr.careco.aaa.ws.Vin> wsSiVinConsulterFlotteParSiren(
        @WebParam(name = "siren", targetNamespace = "http://aaa.asso.fr/sivin/schemas")
        java.lang.String siren
    ) throws BaseDeDonneeInaccessible_Exception, Quota_Exception, NumeroSirenInconnu_Exception;

    @WebResult(name = "return", targetNamespace = "http://aaa.asso.fr/sivin/schemas")
    @Action(input = "urn:WS_SiVin_Consulter_VehiculeParVin", output = "//aaa.asso.fr/sivin/WS_SiVin_ConsulterPortType/WS_SiVin_Consulter_VehiculeParVinResponse", fault = {@FaultAction(className = BaseDeDonneeInaccessible_Exception.class, value = "urn:WS_SiVin_Consulter_VehiculeParVinBaseDeDonneeInaccessible"), @FaultAction(className = Quota_Exception.class, value = "urn:WS_SiVin_Consulter_VehiculeParVinQuota"), @FaultAction(className = NumeroVinInconnu_Exception.class, value = "urn:WS_SiVin_Consulter_VehiculeParVinNumeroVinInconnu")})
    @RequestWrapper(localName = "WS_SiVin_Consulter_VehiculeParVin", targetNamespace = "http://aaa.asso.fr/sivin/schemas", className = "fr.careco.aaa.ws.WSSiVinConsulterVehiculeParVin")
    @WebMethod(operationName = "WS_SiVin_Consulter_VehiculeParVin", action = "urn:WS_SiVin_Consulter_VehiculeParVin")
    @ResponseWrapper(localName = "WS_SiVin_Consulter_VehiculeResponse", targetNamespace = "http://aaa.asso.fr/sivin/schemas", className = "fr.careco.aaa.ws.WSSiVinConsulterVehiculeResponse")
    public fr.careco.aaa.ws.Vehicule wsSiVinConsulterVehiculeParVin(
        @WebParam(name = "vin", targetNamespace = "http://aaa.asso.fr/sivin/schemas")
        java.lang.String vin,
        @WebParam(name = "Nom", targetNamespace = "http://aaa.asso.fr/sivin/schemas")
        java.lang.String nom,
        @WebParam(name = "DateDCG", targetNamespace = "http://aaa.asso.fr/sivin/schemas")
        fr.careco.aaa.ws.Date dateDCG,
        @WebParam(name = "Date1erCir", targetNamespace = "http://aaa.asso.fr/sivin/schemas")
        fr.careco.aaa.ws.Date date1ErCir,
        @WebParam(name = "numeroSerie", targetNamespace = "http://aaa.asso.fr/sivin/schemas")
        java.lang.String numeroSerie
    ) throws BaseDeDonneeInaccessible_Exception, Quota_Exception, NumeroVinInconnu_Exception;
}
