
package fr.asso.aaa.sivin;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.8-patch-01
 * 2014-06-24T14:16:30.943+02:00
 * Generated source version: 2.4.8-patch-01
 */

@WebFault(name = "BaseDeDonneeInaccessible", targetNamespace = "http://aaa.asso.fr/sivin/schemas")
public class BaseDeDonneeInaccessible extends Exception {
    
    private fr.asso.aaa.sivin.schemas.BaseDeDonneeInaccessible baseDeDonneeInaccessible;

    public BaseDeDonneeInaccessible() {
        super();
    }
    
    public BaseDeDonneeInaccessible(String message) {
        super(message);
    }
    
    public BaseDeDonneeInaccessible(String message, Throwable cause) {
        super(message, cause);
    }

    public BaseDeDonneeInaccessible(String message, fr.asso.aaa.sivin.schemas.BaseDeDonneeInaccessible baseDeDonneeInaccessible) {
        super(message);
        this.baseDeDonneeInaccessible = baseDeDonneeInaccessible;
    }

    public BaseDeDonneeInaccessible(String message, fr.asso.aaa.sivin.schemas.BaseDeDonneeInaccessible baseDeDonneeInaccessible, Throwable cause) {
        super(message, cause);
        this.baseDeDonneeInaccessible = baseDeDonneeInaccessible;
    }

    public fr.asso.aaa.sivin.schemas.BaseDeDonneeInaccessible getFaultInfo() {
        return this.baseDeDonneeInaccessible;
    }
}
