
package fr.asso.aaa.sivin;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.8-patch-01
 * 2014-06-24T14:16:30.961+02:00
 * Generated source version: 2.4.8-patch-01
 */

@WebFault(name = "NumeroSirenInconnu", targetNamespace = "http://aaa.asso.fr/sivin/schemas")
public class NumeroSirenInconnu extends Exception {
    
    private fr.asso.aaa.sivin.schemas.NumeroSirenInconnu numeroSirenInconnu;

    public NumeroSirenInconnu() {
        super();
    }
    
    public NumeroSirenInconnu(String message) {
        super(message);
    }
    
    public NumeroSirenInconnu(String message, Throwable cause) {
        super(message, cause);
    }

    public NumeroSirenInconnu(String message, fr.asso.aaa.sivin.schemas.NumeroSirenInconnu numeroSirenInconnu) {
        super(message);
        this.numeroSirenInconnu = numeroSirenInconnu;
    }

    public NumeroSirenInconnu(String message, fr.asso.aaa.sivin.schemas.NumeroSirenInconnu numeroSirenInconnu, Throwable cause) {
        super(message, cause);
        this.numeroSirenInconnu = numeroSirenInconnu;
    }

    public fr.asso.aaa.sivin.schemas.NumeroSirenInconnu getFaultInfo() {
        return this.numeroSirenInconnu;
    }
}
