
package fr.asso.aaa.sivin;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.8-patch-01
 * 2014-06-24T14:16:30.968+02:00
 * Generated source version: 2.4.8-patch-01
 */

@WebFault(name = "NumeroVinInconnu", targetNamespace = "http://aaa.asso.fr/sivin/schemas")
public class NumeroVinInconnu extends Exception {
    
    private fr.asso.aaa.sivin.schemas.NumeroVinInconnu numeroVinInconnu;

    public NumeroVinInconnu() {
        super();
    }
    
    public NumeroVinInconnu(String message) {
        super(message);
    }
    
    public NumeroVinInconnu(String message, Throwable cause) {
        super(message, cause);
    }

    public NumeroVinInconnu(String message, fr.asso.aaa.sivin.schemas.NumeroVinInconnu numeroVinInconnu) {
        super(message);
        this.numeroVinInconnu = numeroVinInconnu;
    }

    public NumeroVinInconnu(String message, fr.asso.aaa.sivin.schemas.NumeroVinInconnu numeroVinInconnu, Throwable cause) {
        super(message, cause);
        this.numeroVinInconnu = numeroVinInconnu;
    }

    public fr.asso.aaa.sivin.schemas.NumeroVinInconnu getFaultInfo() {
        return this.numeroVinInconnu;
    }
}
