
package fr.asso.aaa.sivin;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.8-patch-01
 * 2014-06-24T14:16:30.908+02:00
 * Generated source version: 2.4.8-patch-01
 */

@WebFault(name = "NumeroImmatriculationInconnu", targetNamespace = "http://aaa.asso.fr/sivin/schemas")
public class NumeroImmatriculationInconnu extends Exception {
    
    private fr.asso.aaa.sivin.schemas.NumeroImmatriculationInconnu numeroImmatriculationInconnu;

    public NumeroImmatriculationInconnu() {
        super();
    }
    
    public NumeroImmatriculationInconnu(String message) {
        super(message);
    }
    
    public NumeroImmatriculationInconnu(String message, Throwable cause) {
        super(message, cause);
    }

    public NumeroImmatriculationInconnu(String message, fr.asso.aaa.sivin.schemas.NumeroImmatriculationInconnu numeroImmatriculationInconnu) {
        super(message);
        this.numeroImmatriculationInconnu = numeroImmatriculationInconnu;
    }

    public NumeroImmatriculationInconnu(String message, fr.asso.aaa.sivin.schemas.NumeroImmatriculationInconnu numeroImmatriculationInconnu, Throwable cause) {
        super(message, cause);
        this.numeroImmatriculationInconnu = numeroImmatriculationInconnu;
    }

    public fr.asso.aaa.sivin.schemas.NumeroImmatriculationInconnu getFaultInfo() {
        return this.numeroImmatriculationInconnu;
    }
}
