package fr.asso.aaa.sivin;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.8-patch-01
 * 2014-06-24T14:16:30.975+02:00
 * Generated source version: 2.4.8-patch-01
 * 
 */
@WebService(targetNamespace = "http://aaa.asso.fr/sivin", name = "WS_SiVin_ConsulterPortType")
@XmlSeeAlso({fr.asso.aaa.sivin.schemas.ObjectFactory.class, fr.asso.aaa.sivin.xsd.ObjectFactory.class})
public interface WSSiVinConsulterPortType {

    @WebResult(name = "return", targetNamespace = "http://aaa.asso.fr/sivin/schemas")
    @Action(input = "urn:WS_SiVin_Consulter_VehiculeParImmat", output = "//aaa.asso.fr/sivin/WS_SiVin_ConsulterPortType/WS_SiVin_Consulter_VehiculeParImmatResponse", fault = {@FaultAction(className = NumeroImmatriculationInconnu.class, value = "urn:WS_SiVin_Consulter_VehiculeParImmatNumeroImmatriculationInconnu"), @FaultAction(className = BaseDeDonneeInaccessible.class, value = "urn:WS_SiVin_Consulter_VehiculeParImmatBaseDeDonneeInaccessible"), @FaultAction(className = Quota.class, value = "urn:WS_SiVin_Consulter_VehiculeParImmatQuota")})
    @RequestWrapper(localName = "WS_SiVin_Consulter_VehiculeParImmat", targetNamespace = "http://aaa.asso.fr/sivin/schemas", className = "fr.asso.aaa.sivin.schemas.WSSiVinConsulterVehiculeParImmat")
    @WebMethod(operationName = "WS_SiVin_Consulter_VehiculeParImmat", action = "urn:WS_SiVin_Consulter_VehiculeParImmat")
    @ResponseWrapper(localName = "WS_SiVin_Consulter_VehiculeResponse", targetNamespace = "http://aaa.asso.fr/sivin/schemas", className = "fr.asso.aaa.sivin.schemas.WSSiVinConsulterVehiculeResponse")
    public fr.asso.aaa.sivin.xsd.Vehicule wsSiVinConsulterVehiculeParImmat(
        @WebParam(name = "immat", targetNamespace = "http://aaa.asso.fr/sivin/schemas")
        java.lang.String immat,
        @WebParam(name = "Nom", targetNamespace = "http://aaa.asso.fr/sivin/schemas")
        java.lang.String nom,
        @WebParam(name = "DateDCG", targetNamespace = "http://aaa.asso.fr/sivin/schemas")
        fr.asso.aaa.sivin.xsd.Date dateDCG,
        @WebParam(name = "Date1erCir", targetNamespace = "http://aaa.asso.fr/sivin/schemas")
        fr.asso.aaa.sivin.xsd.Date date1ErCir,
        @WebParam(name = "numeroSerie", targetNamespace = "http://aaa.asso.fr/sivin/schemas")
        java.lang.String numeroSerie
    ) throws NumeroImmatriculationInconnu, BaseDeDonneeInaccessible, Quota;

    @WebResult(name = "return", targetNamespace = "http://aaa.asso.fr/sivin/schemas")
    @Action(input = "urn:WS_SiVin_Consulter_FlotteParSiren", output = "//aaa.asso.fr/sivin/WS_SiVin_ConsulterPortType/WS_SiVin_Consulter_FlotteParSirenResponse", fault = {@FaultAction(className = BaseDeDonneeInaccessible.class, value = "urn:WS_SiVin_Consulter_FlotteParSirenBaseDeDonneeInaccessible"), @FaultAction(className = Quota.class, value = "urn:WS_SiVin_Consulter_FlotteParSirenQuota"), @FaultAction(className = NumeroSirenInconnu.class, value = "urn:WS_SiVin_Consulter_FlotteParSirenNumeroSirenInconnu")})
    @RequestWrapper(localName = "WS_SiVin_Consulter_FlotteParSiren", targetNamespace = "http://aaa.asso.fr/sivin/schemas", className = "fr.asso.aaa.sivin.schemas.WSSiVinConsulterFlotteParSiren")
    @WebMethod(operationName = "WS_SiVin_Consulter_FlotteParSiren", action = "urn:WS_SiVin_Consulter_FlotteParSiren")
    @ResponseWrapper(localName = "WS_SiVin_Consulter_FlotteParSirenResponse", targetNamespace = "http://aaa.asso.fr/sivin/schemas", className = "fr.asso.aaa.sivin.schemas.WSSiVinConsulterFlotteParSirenResponse")
    public java.util.List<fr.asso.aaa.sivin.schemas.Vin> wsSiVinConsulterFlotteParSiren(
        @WebParam(name = "siren", targetNamespace = "http://aaa.asso.fr/sivin/schemas")
        java.lang.String siren
    ) throws BaseDeDonneeInaccessible, Quota, NumeroSirenInconnu;

    @WebResult(name = "return", targetNamespace = "http://aaa.asso.fr/sivin/schemas")
    @Action(input = "urn:WS_SiVin_Consulter_VehiculeParVin", output = "//aaa.asso.fr/sivin/WS_SiVin_ConsulterPortType/WS_SiVin_Consulter_VehiculeParVinResponse", fault = {@FaultAction(className = BaseDeDonneeInaccessible.class, value = "urn:WS_SiVin_Consulter_VehiculeParVinBaseDeDonneeInaccessible"), @FaultAction(className = Quota.class, value = "urn:WS_SiVin_Consulter_VehiculeParVinQuota"), @FaultAction(className = NumeroVinInconnu.class, value = "urn:WS_SiVin_Consulter_VehiculeParVinNumeroVinInconnu")})
    @RequestWrapper(localName = "WS_SiVin_Consulter_VehiculeParVin", targetNamespace = "http://aaa.asso.fr/sivin/schemas", className = "fr.asso.aaa.sivin.schemas.WSSiVinConsulterVehiculeParVin")
    @WebMethod(operationName = "WS_SiVin_Consulter_VehiculeParVin", action = "urn:WS_SiVin_Consulter_VehiculeParVin")
    @ResponseWrapper(localName = "WS_SiVin_Consulter_VehiculeResponse", targetNamespace = "http://aaa.asso.fr/sivin/schemas", className = "fr.asso.aaa.sivin.schemas.WSSiVinConsulterVehiculeResponse")
    public fr.asso.aaa.sivin.xsd.Vehicule wsSiVinConsulterVehiculeParVin(
        @WebParam(name = "vin", targetNamespace = "http://aaa.asso.fr/sivin/schemas")
        java.lang.String vin,
        @WebParam(name = "Nom", targetNamespace = "http://aaa.asso.fr/sivin/schemas")
        java.lang.String nom,
        @WebParam(name = "DateDCG", targetNamespace = "http://aaa.asso.fr/sivin/schemas")
        fr.asso.aaa.sivin.xsd.Date dateDCG,
        @WebParam(name = "Date1erCir", targetNamespace = "http://aaa.asso.fr/sivin/schemas")
        fr.asso.aaa.sivin.xsd.Date date1ErCir,
        @WebParam(name = "numeroSerie", targetNamespace = "http://aaa.asso.fr/sivin/schemas")
        java.lang.String numeroSerie
    ) throws BaseDeDonneeInaccessible, Quota, NumeroVinInconnu;
}
