package fr.careco.blueway.ws.b2b;

import javax.ejb.Local;
import javax.ejb.Remote;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-06-17T12:16:52.810+02:00
 * Generated source version: 3.0.0
 * 
 */
@WebService(targetNamespace = "http://carecoprod.blueway.fr:8180/engine53/52", name = "AAA00_WsB2BPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@Local
public interface AAA00WsB2BPortType {

    @WebResult(name = "AAA00_WsB2BOUT", targetNamespace = "http://carecoprod.blueway.fr:8180/engine53/52", partName = "AAA00_WsB2BReturn")
    @WebMethod(operationName = "AAA00_WsB2B", action = "AAA00_WsB2B#1#EAII")
    public AAA00WsB2BOUT aaa00WsB2B(
        @WebParam(partName = "AAA00_WsB2BInput", name = "AAA00_WsB2BIN", targetNamespace = "http://carecoprod.blueway.fr:8180/engine53/52")
        AAA00WsB2BIN aaa00WsB2BInput
    );
}
