package fr.careco.blueway.ws.b2b;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-06-17T12:16:52.821+02:00
 * Generated source version: 3.0.0
 * 
 */
@WebServiceClient(name = "AAA00_WsB2B", 
                  wsdlLocation = "file:/home/nicolas/Bureau/Careco/Pack Careco/WSDL_B2B.wsdl",
                  targetNamespace = "http://carecoprod.blueway.fr:8180/engine53/52") 
public class AAA00WsB2B extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://carecoprod.blueway.fr:8180/engine53/52", "AAA00_WsB2B");
    public final static QName AAA00WsB2BPort = new QName("http://carecoprod.blueway.fr:8180/engine53/52", "AAA00_WsB2BPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/nicolas/Bureau/Careco/Pack Careco/WSDL_B2B.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AAA00WsB2B.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/nicolas/Bureau/Careco/Pack Careco/WSDL_B2B.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AAA00WsB2B(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AAA00WsB2B(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AAA00WsB2B() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AAA00WsB2B(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AAA00WsB2B(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AAA00WsB2B(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns AAA00WsB2BPortType
     */
    @WebEndpoint(name = "AAA00_WsB2BPort")
    public AAA00WsB2BPortType getAAA00WsB2BPort() {
        return super.getPort(AAA00WsB2BPort, AAA00WsB2BPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AAA00WsB2BPortType
     */
    @WebEndpoint(name = "AAA00_WsB2BPort")
    public AAA00WsB2BPortType getAAA00WsB2BPort(WebServiceFeature... features) {
        return super.getPort(AAA00WsB2BPort, AAA00WsB2BPortType.class, features);
    }

}
