
package fr.careco.blueway.ws.b2b;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-06-17T12:16:52.817+02:00
 * Generated source version: 3.0.0
 * 
 */
 
public class AAA00WsB2BPortType_AAA00WsB2BPort_Server{

    protected AAA00WsB2BPortType_AAA00WsB2BPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new AAA00_WsB2BPortImpl();
        String address = "http://carecoprod.blueway.fr:8180/engine53/52/WebserviceLauncher";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new AAA00WsB2BPortType_AAA00WsB2BPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
