package fr.careco.blueway.ws.b2c;

import javax.ejb.Local;
import javax.ejb.Remote;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-06-13T15:57:13.275+02:00
 * Generated source version: 3.0.0
 * 
 */
@WebService(targetNamespace = "http://carecoprod.blueway.fr:8180/engine53/52", name = "ProxyWsAAAB2CPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@Local
public interface ProxyWsAAAB2CPortType {

    @WebResult(name = "AAA00_WsB2COUT", targetNamespace = "http://carecoprod.blueway.fr:8180/engine53/52", partName = "AAA00_WsB2CReturn")
    @WebMethod(operationName = "AAA00_WsB2C", action = "AAA00_WsB2C#1#EAII")
    public AAA00WsB2COUT aaa00WsB2C(
        @WebParam(partName = "AAA00_WsB2CInput", name = "AAA00_WsB2CIN", targetNamespace = "http://carecoprod.blueway.fr:8180/engine53/52")
        AAA00WsB2CIN aaa00WsB2CInput
    );
}
